import { Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700', '800']
});
export const metadata = {
  title: "Age Calculator",
  description: "Age Calculator Generated by @yazn_108",
  Image: ""
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href={"/favicon-32x32.png"} />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
