import { Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700', '800']
});
export const metadata = {
  title: "Age Calculator",
  description: "Age Calculator Generated by @yazn_108",
  Image: ""
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href={"/favicon-32x32.png"} />
        <title>Age Calculator</title>
        <meta name="description" content="Age Calculator Generated by @yazn_108" />
        <meta property="og:url" content="https://yazn-age-calculator.vercel.app/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Age Calculator" />
        <meta property="og:description" content="Age Calculator Generated by @yazn_108" />
        <meta property="og:image" content="https://opengraph.b-cdn.net/production/documents/97afd0ff-f4ba-4ba6-8da9-cae3b4c536e3.png?token=OS9X1TflOFdWH-YqyFw0aW4Boo-QiwdFmigZUz6x_-U&height=576&width=1200&expires=33245595404" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="yazn-age-calculator.vercel.app" />
        <meta property="twitter:url" content="https://yazn-age-calculator.vercel.app/" />
        <meta name="twitter:title" content="Age Calculator" />
        <meta name="twitter:description" content="Age Calculator Generated by @yazn_108" />
        <meta name="twitter:image" content="https://opengraph.b-cdn.net/production/documents/97afd0ff-f4ba-4ba6-8da9-cae3b4c536e3.png?token=OS9X1TflOFdWH-YqyFw0aW4Boo-QiwdFmigZUz6x_-U&height=576&width=1200&expires=33245595404" />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
